Numpy

In [3]:
import numpy as np
a = np.array([1,2,3])

b = np.array([[11,12,13],[21,22,23],[31,32,33]])
b[2,2] #b[1][2]



np.int64(33)

In [4]:
np.arange(1,10,1)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.linspace(1,9,10)


array([1.        , 1.88888889, 2.77777778, 3.66666667, 4.55555556,
       5.44444444, 6.33333333, 7.22222222, 8.11111111, 9.        ])

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((5))

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.random.rand()


0.8461348705528281

In [12]:
np.random.rand(10,10)

array([[0.67639406, 0.29181174, 0.63167073, 0.506169  , 0.8002515 ,
        0.33903683, 0.25951542, 0.05396915, 0.46555861, 0.65706307],
       [0.20103096, 0.40963968, 0.82903261, 0.22417586, 0.96803253,
        0.32254529, 0.41687293, 0.61692778, 0.39630724, 0.68768138],
       [0.58763147, 0.624105  , 0.71332888, 0.82302758, 0.01909991,
        0.0106476 , 0.50570846, 0.52028715, 0.77761626, 0.18428401],
       [0.38940202, 0.36338673, 0.60070282, 0.13045498, 0.37693013,
        0.21031397, 0.14110121, 0.24424518, 0.4370283 , 0.85125828],
       [0.24846554, 0.48709444, 0.08807973, 0.69357805, 0.20946162,
        0.3435283 , 0.11567948, 0.39657423, 0.2133013 , 0.37931719],
       [0.87773052, 0.02092558, 0.12740218, 0.98674722, 0.07817688,
        0.51506097, 0.60617642, 0.06662771, 0.12661846, 0.17673377],
       [0.05311256, 0.20357435, 0.26234706, 0.50365748, 0.47495181,
        0.35831284, 0.07134242, 0.87023824, 0.96723957, 0.62061041],
       [0.60601132, 0.28878732, 0.7440008

In [13]:
np.random.randn(5,5)

array([[-1.49500682,  0.74770229, -2.07086873,  0.94125034,  1.5314443 ],
       [ 0.55805596, -1.10767916, -0.95910251,  0.21054886, -0.06176264],
       [ 1.84068521,  0.08930602,  0.28290088, -0.58560281,  1.80051393],
       [-0.17299354,  1.68378611,  0.49964921, -0.78078924,  0.80967799],
       [-1.06798864,  1.21337949, -0.785334  ,  1.55083142, -1.90033135]])

In [14]:
np.random.randint(1,5)


1

In [15]:
np.random.randint(1,5,[5,5])


array([[2, 1, 3, 3, 2],
       [3, 1, 2, 1, 2],
       [2, 3, 1, 4, 3],
       [1, 3, 4, 4, 4],
       [4, 1, 3, 3, 2]], dtype=int32)

Array Methods


In [16]:
data = [1,4,3,5]
arr = np.array(data)
print(arr)
print(arr.dtype)
print(arr.shape)

[1 4 3 5]
int64
(4,)


In [17]:
a = np.random.rand(1000)
b = np.random.randn(1000)
a.min()


np.float64(0.00019927061310409666)

In [18]:
a.max()

np.float64(0.9991109943499963)

In [19]:
a.mean()

np.float64(0.4883638095110929)

In [20]:
b.min()

np.float64(-3.3018772552801474)

In [22]:
b.max()

np.float64(3.3112704853649713)

In [23]:
b.mean()


np.float64(-0.04278480585114291)

In [24]:
c = np.random.rand(4)

In [25]:
c = np.random.rand(4)


In [26]:
c.argmin()


np.int64(2)

In [27]:
c.argmax()

np.int64(1)

In [29]:
d = c.reshape(2,2)
print(d.shape)
d


(2, 2)


array([[0.60930082, 0.96269184],
       [0.10501534, 0.74440589]])

In [30]:
c.reshape(4)

array([0.60930082, 0.96269184, 0.10501534, 0.74440589])

In [31]:
c.reshape(2,2)


array([[0.60930082, 0.96269184],
       [0.10501534, 0.74440589]])

In [32]:
c.flatten()


array([0.60930082, 0.96269184, 0.10501534, 0.74440589])

In [33]:
e = np.array([0])
f = np.array([0.])
e.dtype

dtype('int64')

In [34]:
f.dtype


dtype('float64')

Indexing and broadcasting

In [35]:
a = np.arange(5)
a


array([0, 1, 2, 3, 4])

In [36]:
a[:]


array([0, 1, 2, 3, 4])

In [37]:
a[2]

np.int64(2)

In [38]:
a[2:4]


array([2, 3])

In [39]:
a[-1]


np.int64(4)

In [40]:
a[2:]

array([2, 3, 4])

In [41]:
a[:2]

array([0, 1])

In [42]:
a[:2]=10


In [45]:
a = np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
b = a[2:7]
b


array([2, 3, 4, 5, 6])

In [47]:
b[2:5]=10
b

array([ 2,  3, 10, 10, 10])

In [48]:
a

array([ 0,  1,  2,  3, 10, 10, 10,  7,  8,  9])

In [49]:
c = a.copy()
c


array([ 0,  1,  2,  3, 10, 10, 10,  7,  8,  9])

In [50]:
c[4:7]=0
c

array([0, 1, 2, 3, 0, 0, 0, 7, 8, 9])

In [51]:
a

array([ 0,  1,  2,  3, 10, 10, 10,  7,  8,  9])

2-D

In [52]:
a = np.random.rand(5,5)
a

array([[0.63660821, 0.94286063, 0.05723887, 0.48337022, 0.37656015],
       [0.27822094, 0.58466972, 0.95767544, 0.56377237, 0.6898407 ],
       [0.8101932 , 0.20776825, 0.16276586, 0.65978913, 0.2665769 ],
       [0.09256138, 0.49802179, 0.59836187, 0.31616397, 0.12335901],
       [0.14605191, 0.44828015, 0.75416045, 0.47422571, 0.55524367]])

In [53]:
a[0]


array([0.63660821, 0.94286063, 0.05723887, 0.48337022, 0.37656015])

In [54]:
a[:,0]

array([0.63660821, 0.27822094, 0.8101932 , 0.09256138, 0.14605191])

In [55]:
a[1:4,1:4]=10
a

array([[ 0.63660821,  0.94286063,  0.05723887,  0.48337022,  0.37656015],
       [ 0.27822094, 10.        , 10.        , 10.        ,  0.6898407 ],
       [ 0.8101932 , 10.        , 10.        , 10.        ,  0.2665769 ],
       [ 0.09256138, 10.        , 10.        , 10.        ,  0.12335901],
       [ 0.14605191,  0.44828015,  0.75416045,  0.47422571,  0.55524367]])

Logical operator to filter


In [56]:
a = np.random.randn(5,5)
a

array([[ 0.86699957, -0.32596745, -0.37019049, -1.1548374 ,  1.30740954],
       [-0.99211059,  1.73193873, -1.66946956, -0.69236463,  0.54562927],
       [ 0.29088699, -1.17627173, -2.09439385,  1.20292097, -0.18383597],
       [-0.69080967, -0.24997005,  0.2856522 ,  0.35198411, -1.0234133 ],
       [ 0.41173367,  0.43453916, -1.49722429, -0.57406719, -0.6268944 ]])

In [57]:
a>0


array([[ True, False, False, False,  True],
       [False,  True, False, False,  True],
       [ True, False, False,  True, False],
       [False, False,  True,  True, False],
       [ True,  True, False, False, False]])

In [58]:
a[a>0]=10
a


array([[10.        , -0.32596745, -0.37019049, -1.1548374 , 10.        ],
       [-0.99211059, 10.        , -1.66946956, -0.69236463, 10.        ],
       [10.        , -1.17627173, -2.09439385, 10.        , -0.18383597],
       [-0.69080967, -0.24997005, 10.        , 10.        , -1.0234133 ],
       [10.        , 10.        , -1.49722429, -0.57406719, -0.6268944 ]])

Operator

In [60]:
a = np.array([0,2,4,6,8])
b = np.array([1,3,5,7,9])
c = a
c

array([0, 2, 4, 6, 8])

In [61]:
d = b - 1
c = d==a
c.any()


np.True_

In [62]:
d = np.array([0,5,6,9,9])
c = d==a
c.any()


np.True_

In [63]:
c.all()

np.False_

Function

In [64]:
a = np.arange(0,1,0.1)
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [65]:
np.square(a)


array([0.  , 0.01, 0.04, 0.09, 0.16, 0.25, 0.36, 0.49, 0.64, 0.81])

In [66]:
np.sin(a)

array([0.        , 0.09983342, 0.19866933, 0.29552021, 0.38941834,
       0.47942554, 0.56464247, 0.64421769, 0.71735609, 0.78332691])

In [67]:
np.exp(a)


array([1.        , 1.10517092, 1.22140276, 1.34985881, 1.4918247 ,
       1.64872127, 1.8221188 , 2.01375271, 2.22554093, 2.45960311])

Linear algebra


In [68]:
# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
# Matrix multiplication
C = np.dot(A, B)
# Or equivalently: C = A @ B
print(C)


[[19 22]
 [43 50]]


In [69]:
# Define a matrix
A = np.array([[1, 2], [3, 4]])
# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[-0.37228132  5.37228132]

Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [71]:
# Define a matrix
A = np.array([[1, 2, 3], [4, 5, 6]])
# Compute SVD
U, S, V = np.linalg.svd(A)
print("U:")
print(U)
print("\nS:")
print(S)
print("\nV:")
print(V)


U:
[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]

S:
[9.508032   0.77286964]

V:
[[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


 Pandas

In [72]:
import pandas as pd
pd.Series([6,2,3])

0    6
1    2
2    3
dtype: int64

In [73]:
pd.Series(data=[6,2,3],index=['abc','def','ghi'])

abc    6
def    2
ghi    3
dtype: int64

In [74]:
a = pd.Series(data=[6,2,3],index=['abc','def','ghi'])
a['abc']

np.int64(6)

In [75]:
6
pd.Series([6,2,3],['abc','def','ghi'])

abc    6
def    2
ghi    3
dtype: int64

In [78]:
pd.Series(np.array([6,2,3]),['abc','def','ghi'])


abc    6
def    2
ghi    3
dtype: int64

In [79]:
dict = {'abc':6,'def':2,'ghi':3}
dict

{'abc': 6, 'def': 2, 'ghi': 3}

In [80]:
pd.Series(dict)

abc    6
def    2
ghi    3
dtype: int64

In [81]:
a = [2,3,5]
b = pd.Series([sum,min,max])
b[0](a)


10

In [82]:
a = {'a':5,'b':3,'c':10,'d':20}
b = {'a':2,'b':3,'c':10}
#a+b
pd.Series(a)+pd.Series(b)


a     7.0
b     6.0
c    20.0
d     NaN
dtype: float64


Dataframe

In [83]:
pd.DataFrame(data=[[1,2,3],[4,5,6],[7,8,9]])


0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [84]:
pd.DataFrame(data=[[1,2,3],[4,5,6],[7,8,9]],columns=['y1','y2','y3'])


y1  y2  y3
0   1   2   3
1   4   5   6
2   7   8   9

In [85]:
pd.DataFrame(data=[[1,2,3],[4,5,6],[7,8,9]],index=['x1','x2','x3'])


0  1  2
x1  1  2  3
x2  4  5  6
x3  7  8  9

In [86]:
pd.DataFrame(data=[[1,2,3],[4,5,6],[7,8,9]],index=['x1','x2','x3'],columns=['y1','y2','y3'])

y1  y2  y3
x1   1   2   3
x2   4   5   6
x3   7   8   9

In [88]:
a = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],['x1','x2','x3'],['y1','y2','y3'])
a

y1  y2  y3
x1   1   2   3
x2   4   5   6
x3   7   8   9

 Indexing

In [89]:
a['y1']

x1    1
x2    4
x3    7
Name: y1, dtype: int64

In [90]:
a.y1

x1    1
x2    4
x3    7
Name: y1, dtype: int64

In [92]:
a.loc['x2']

y1    4
y2    5
y3    6
Name: x2, dtype: int64

In [93]:
a.iloc[0]

y1    1
y2    2
y3    3
Name: x1, dtype: int64

In [94]:
a.loc['x1','y1']


np.int64(1)

In [95]:
a.iloc[1,1]


np.int64(5)

In [96]:
a.loc[['x1','x3'],['y1','y3']]


y1  y3
x1   1   3
x3   7   9

In [97]:
a.iloc[[0,1],[0,1]]


y1  y2
x1   1   2
x2   4   5

In [98]:
a

y1  y2  y3
x1   1   2   3
x2   4   5   6
x3   7   8   9

In [99]:
# adding new column
a['sum']=a['y1']+a['y2']+a['y3']
a


y1  y2  y3  sum
x1   1   2   3    6
x2   4   5   6   15
x3   7   8   9   24

In [100]:
#drop column
a.drop('y3',axis=1)


y1  y2  sum
x1   1   2    6
x2   4   5   15
x3   7   8   24

In [101]:
#drop row
a.drop('x2',axis=0)

y1  y2  y3  sum
x1   1   2   3    6
x3   7   8   9   24

In [102]:
#selection based on codition
a>5


y1     y2     y3   sum
x1  False  False  False  True
x2  False  False   True  True
x3   True   True   True  True

In [103]:
a[a>5]

y1   y2   y3  sum
x1  NaN  NaN  NaN    6
x2  NaN  NaN  6.0   15
x3  7.0  8.0  9.0   24

In [104]:
a[a['y2']>5]


y1  y2  y3  sum
x3   7   8   9   24

In [105]:
a[(a['y2']>2) & (a['y1']<5) ]


y1  y2  y3  sum
x2   4   5   6   15

In [106]:
a


y1  y2  y3  sum
x1   1   2   3    6
x2   4   5   6   15
x3   7   8   9   24

In [107]:
a.reset_index()


index  y1  y2  y3  sum
0    x1   1   2   3    6
1    x2   4   5   6   15
2    x3   7   8   9   24

In [108]:
a.set_index('sum')


y1  y2  y3
sum            
6     1   2   3
15    4   5   6
24    7   8   9

In [109]:
b = a.set_index('sum')

Multi index

In [111]:
first = [1,1,1,1,2,2,2,2]
second = [1,1,2,2,1,1,2,2]
third = [1,2,1,2,1,2,1,2]
fourth=[1,2,1,1,2,3,1,2]
ind = list(zip(first,second,third,fourth))
ind = pd.MultiIndex.from_tuples(ind)
ind


MultiIndex([(1, 1, 1, 1),
            (1, 1, 2, 2),
            (1, 2, 1, 1),
            (1, 2, 2, 1),
            (2, 1, 1, 2),
            (2, 1, 2, 3),
            (2, 2, 1, 1),
            (2, 2, 2, 2)],
           )

In [112]:
a = pd.DataFrame(np.random.rand(8,3),index=ind,columns=['x1','x2','x3'])
a


x1        x2        x3
1 1 1 1  0.749012  0.401507  0.031612
    2 2  0.772220  0.470643  0.825894
  2 1 1  0.674849  0.871578  0.757784
    2 1  0.939153  0.623719  0.750947
2 1 1 2  0.547571  0.896925  0.441245
    2 3  0.052321  0.330707  0.467821
  2 1 1  0.740171  0.590348  0.647334
    2 2  0.331717  0.312306  0.583762

In [113]:
a.loc[1]

x1        x2        x3
1 1 1  0.749012  0.401507  0.031612
  2 2  0.772220  0.470643  0.825894
2 1 1  0.674849  0.871578  0.757784
  2 1  0.939153  0.623719  0.750947

In [114]:
a.loc[1].loc[2]

x1        x2        x3
1 1  0.674849  0.871578  0.757784
2 1  0.939153  0.623719  0.750947

In [ ]:
a.loc[1].loc[2].loc[1]
